create files & change files
yuya-oki/chat_space pull request #9
Opened 2019-03-28 10:22 UTC by yuya-oki

WHAT
インクリメンタルサーチの実装
WHY
グループメンバーを検索しやすいようにするため

2019-03-28 10:23 UTC, hiroki5123 commented
実際に動いている部分のGIFをこちらに添付して下さい。

2019-03-28 10:25 UTC, ghost requested changes

2019-03-28 10:25 UTC, hiroki5123 commented on chat-space/app/controllers/registrations_controller.rb
> +    return
ここでreturnを入れている理由はなんですか？

2019-03-28 10:25 UTC, hiroki5123 commented on chat-space/app/assets/javascripts/search.js
> +      console.log
削除しましょう

2019-03-30 06:40 UTC, yuya-oki commented
https://gyazo.com/c090e10459783697b01c260d7f167632

2019-03-30 06:42 UTC, yuya-oki commented
console.logは削除済み
returnはエラーが起こり、調べてからやりましたが関係がなかったので別のファイルを編集済み
実際に動かしていますが、他のユーザーが出てこないことに加えて自分もチャットメンバーに入っていません。

2019-03-30 06:46 UTC, kuroko918 commented on chat-space/app/controllers/registrations_controller.rb
> +    return
こちらはいらないと思うので消しましょう！

2019-03-30 06:46 UTC, kuroko918 commented on chat-space/app/controllers/registrations_controller.rb
> +    return
こちらも消しておきましょう！

2019-03-30 06:46 UTC, kuroko918 commented on chat-space/app/controllers/users_controller.rb
> +      return
こちらも消しておきましょう！

2019-03-30 06:46 UTC, kuroko918 commented
こちらインクリメンタルサーチがきちんと動いていますか？
gif画像で確認できないのですが…

2019-03-30 06:53 UTC, yuya-oki commented
指摘のあったreturnは削除しました。
インクリメンタルサーチは動いていないのでどの部分を修正した方がいいのかご教授願えますか？

2019-03-30 06:57 UTC, kuroko918 commented
コードだけだと、エラーが何も確認できないので、お手数ですが、CONNECTで見ていただいてもよろしいでしょうか？

2019-03-30 06:58 UTC, yuya-oki commented
わかりました！ありがとうございます。

2019-03-30 12:15 UTC, yuya-oki commented
https://gyazo.com/d9d5a931d69e1c2b6b9f56dc88bf57a1

2019-03-30 12:15 UTC, yuya-oki commented
WHAT
インクリメンタルサーチの実装
WHY
検索結果をわかりやすくするため

2019-03-30 12:25 UTC, kuroko918 reviewed
一旦修正お願いします！

2019-03-30 12:25 UTC, kuroko918 commented on chat-space/app/assets/javascripts/index.js
> +  $(function() {
1行目に`$(function() {`は記述してあり被っているので、こちらの記述は削除しておきましょう！

2019-03-30 12:25 UTC, kuroko918 commented on chat-space/app/assets/javascripts/index.js
> +  $(function() {
こちらも同様に消しておきましょう！

2019-03-30 12:25 UTC, kuroko918 commented on chat-space/app/controllers/users_controller.rb
> +      format.html {redirect_to root_path}
`format.html {redirect_to root_path}`は必要ですか？
消してエラーが出るようであれば、`format.html`だけ残しておきましょう！

2019-03-30 12:25 UTC, kuroko918 commented on chat-space/app/controllers/users_controller.rb
> +    @users = User.where('name LIKE(?)', "#{params[:keyword]}%")
ここは`"%#{params[:keyword]}%"`ではないですか？
頭の%がなくなってしまっています。

2019-03-30 12:25 UTC, kuroko918 commented on chat-space/app/views/groups/_form.html.haml
> +      = f.label :"グループ名", class: 'chat-group-form__label'
ここはlabelタグである必要はありますか？
グループ名というidを持つinputはないようですが？

2019-03-30 12:25 UTC, kuroko918 commented on chat-space/app/views/groups/_form.html.haml
> +      %label.chat-group-form__label{for: 'chat_group_チャットメンバーを追加'} チャットメンバーを追加
こちらも同様にchat_group_チャットメンバーを追加というidを持つinputはないようですが。

2019-03-30 12:25 UTC, kuroko918 commented on chat-space/app/views/groups/_form.html.haml
> +      %label.chat-group-form__label チャットメンバー
こちらもlabelタグは必要ですか？そもそもforオプションもないようなので

2019-03-30 12:25 UTC, kuroko918 commented on chat-space/app/assets/javascripts/message.js
> +      return false;
この`return false`は必要ですか？

2019-03-30 12:25 UTC, kuroko918 commented on chat-space/app/assets/javascripts/index.js
> +                  <a class="user_search_add chat-group-user__btn chat-group-user__btn--add" data-user-id="${user.id}" data-user-name="${user.name}">追加
ここはsrcオプションもないようですが、aタグである必要はありますか？

2019-03-30 12:25 UTC, kuroko918 commented on chat-space/app/assets/javascripts/index.js
> +                <a class='user_search_remove chat-group-user__btn chat-group-user__btn--remove js-remove-btn'>削除</a>
ここはsrcオプションもないようですが、aタグである必要はありますか？

2019-03-30 12:38 UTC, yuya-oki commented
指摘された部分を修正しました。

2019-03-30 12:43 UTC, miyagit commented on chat-space/app/controllers/users_controller.rb
> +    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%")
こちらログインユーザーは含めないようにしましょう。

2019-03-30 13:03 UTC, yuya-oki commented on chat-space/app/controllers/users_controller.rb
> +    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%")
ログインユーザーを除外するメソッドなどありますか？

2019-04-01 10:03 UTC, yuya-oki commented
インクリメンタルサーチの実装完了
ユーザー追加ボタンを押した後にビューの追加可能
ユーザー検索の際にログインユーザーを含めないようにするメソッドなどがわからなかった。

2019-04-01 10:11 UTC, TOMARUMARU commented on chat-space/app/controllers/users_controller.rb
> +    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%").except(current_user.name)
nameよりidの方が一意性の観点からbetterです。where.notで弾きましょう

2019-04-01 10:16 UTC, yuya-oki commented
指摘部分の修正

2019-04-01 10:22 UTC, TOMARUMARU reviewed
先の変更だとうまく動かなくなると思いますが、動いていますか？
一回一回動作確認を行ってください

2019-04-01 10:23 UTC, TOMARUMARU commented on chat-space/app/controllers/users_controller.rb
> +    @users = User.where('id LIKE(?)', "%#{params[:keyword]}%").where.not(current_user: nil)
検索はnameじゃないと動かないはずです

2019-04-01 10:32 UTC, yuya-oki commented on chat-space/app/controllers/users_controller.rb
> +    @users = User.where('id LIKE(?)', "%#{params[:keyword]}%").where.not(current_user: nil)
whereとwhere notは一緒に使うのでしょうか？
一緒に使うと検索が行われなくなってしまいます。

2019-04-01 10:57 UTC, TOMARUMARU commented on chat-space/app/controllers/users_controller.rb
> +    @users = User.where('name LIKE(?) and id != ?', "%#{params[:keyword]}%", current_user)
@users = User.where('name LIKE(?) and id != ?', "%#{params[:keyword]}%").where.not(user_id: current_user.id)で動きませんか？

2019-04-01 11:01 UTC, yuya-oki commented on chat-space/app/controllers/users_controller.rb
> +    @users = User.where('name LIKE(?) and id != ?', "%#{params[:keyword]}%", current_user)
指摘のある通りにコードを書き直してやってみましたが動かないですね。

2019-04-01 11:06 UTC, TOMARUMARU commented on chat-space/app/controllers/users_controller.rb
> +    @users = User.where('name LIKE(?) and id != ?', "%#{params[:keyword]}%", current_user)
ああ、すみません、
@users = User.where('name LIKE(?) and id != ?', "%#{params[:keyword]}%").where.not(id: current_user.id) ですね。

どこで動かないのか、どのようなエラーが出るのか、どのような値が取れていないのか、正確に教えてください

2019-04-01 11:48 UTC, yuya-oki commented on chat-space/app/controllers/users_controller.rb
> +    @users = User.where('name LIKE(?) and id != ?', "%#{params[:keyword]}%", current_user)
検索を行おうとメンバー追加の欄に入力するとユーザー検索に失敗しましたというアラートが出てきまして、ターミナルを見るとActiveRecord::PreparedStatementInvalid (wrong number of bind variables (1 for 2) in: name LIKE(?) and id != ?)というエラーが出ています。

2019-04-01 12:10 UTC, TOMARUMARU commented on chat-space/app/controllers/users_controller.rb
> +    @users = User.where('name LIKE(?) and id != ?', "%#{params[:keyword]}%", current_user)
でしたら最初の記述の
@users = User.where('name LIKE(?)', "%#{params[:keyword]}%").where.not(id: current_user.id)で良いのではないでしょうか？

2019-04-01 12:21 UTC, yuya-oki commented
and id != ?を消して見るとうまくいきました。

2019-04-01 12:22 UTC, TOMARUMARU approved these changes
よかったです！LGTM

2019-04-01 12:26 UTC, yuya-oki commented
ありがとうございました！

2019-04-01 12:26 UTC, merged